name: Dev Deploy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "iqw-personal-site-backend-dev"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
